services:
    gamma.listener.requestresponse.stopwatch.slow:
        class: Gamma\Framework\Listener\TrackDurationListener
        arguments: [ @gamma.logger.stopwatch.slow]
        tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    gamma.listener.requestresponse.stopwatch:
        class: Gamma\Framework\Listener\TrackDurationListener
        arguments: [ @gamma.logger.stopwatch]
        tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    symfony.stopwatch.service:
        class: Symfony\Component\Stopwatch\Stopwatch

    gamma.logger.stopwatch:
        class: Gamma\Framework\Service\LoggerStopwatch
        arguments: [ @symfony.stopwatch.service, @logger, %stopwatch_enable% ]
        tags:
            - { name: monolog.logger, channel: api }

    gamma.logger.stopwatch.slow:
        class: Gamma\Framework\Service\LoggerStopwatchSlow
        arguments: [ @symfony.stopwatch.service, @logger, %stopwatch_enable%,  %stopwatch_slow_time_limit%]
        tags:
            - { name: monolog.logger, channel: api_slow }